"""The database and the models agree about what things are called.

``NAMING_CONVENTION`` sat in ``models/meta.py`` unbound for the life of the
project, so every constraint was named by hand and nothing noticed when a
name drifted -- three owner foreign keys were missing their referred-table
suffix and five constraints still carried Postgres defaults. These tests are
what makes ``--autogenerate`` trustworthy from here on: if the models and the
migrations disagree about a name, the next autogenerated migration proposes
dropping and recreating a constraint, and that is the kind of diff nobody
reads carefully by the tenth time they see it.
"""

import sqlalchemy

from menage2.models.meta import NAMING_CONVENTION, Base


def test_naming_convention_is_bound():
    """A DeclarativeBase makes its own MetaData unless told otherwise."""
    assert Base.metadata.naming_convention == NAMING_CONVENTION


def test_no_constraint_name_is_double_prefixed():
    """`ck_%(constraint_name)s` re-prefixes a name that already has one.

    Spelling a check constraint `ck_absences_dates` rather than `dates`
    yields `ck_absences_ck_absences_dates`, which the database never sees
    because the migration hand-typed the short form.
    """
    for table in Base.metadata.tables.values():
        for constraint in table.constraints:
            name = str(getattr(constraint, "name", "") or "")
            prefix = name.split("_")[0]
            assert not name.startswith(f"{prefix}_{table.name}_{prefix}_"), name


def test_constraint_names_match_the_database(dbengine):
    """Every name the models generate is a name the migrations created."""
    with dbengine.connect() as connection:
        rows = connection.execute(
            sqlalchemy.text(
                "SELECT conrelid::regclass::text, conname FROM pg_constraint "
                "WHERE connamespace = 'public'::regnamespace"
            )
        ).all()
    in_database: dict[str, set[str]] = {}
    for table_name, constraint_name in rows:
        in_database.setdefault(table_name, set()).add(constraint_name)

    for name, table in sorted(Base.metadata.tables.items()):
        expected = {str(c.name) for c in table.constraints if getattr(c, "name", None)}
        assert expected <= in_database.get(name, set()), name
