"""add recipe active flag

Revision ID: 05f80527f85f
Revises: a6f2d1215b8b
Create Date: 2023-08-07 14:47:04.465216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f80527f85f'
down_revision = 'a6f2d1215b8b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('active', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'active')
    # ### end Alembic commands ###
