"""add config items

Revision ID: 3180de9cf11d
Revises: 89646db6e305
Create Date: 2023-08-19 07:28:31.007416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3180de9cf11d'
down_revision = '89646db6e305'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_items',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'value', name=op.f('pk_config_items'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_items')
    # ### end Alembic commands ###
