"""introduce config for rtm

Revision ID: 0c8307e920e3
Revises: 3180de9cf11d
Create Date: 2023-12-28 10:09:16.572363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8307e920e3'
down_revision = '3180de9cf11d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('config_items', 'value',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('config_items', 'value',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
