"""add ingredient tags

Revision ID: 19b0c0697f0c
Revises: 3180de9cf11d
Create Date: 2024-12-27 17:40:24.605431

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "19b0c0697f0c"
down_revision = "3180de9cf11d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ingredients", sa.Column("tags", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingredients", "tags")
    # ### end Alembic commands ###
