"""add recipe text

Revision ID: b7f3043fad27
Revises: 19b0c0697f0c
Create Date: 2025-01-05 10:51:59.525006

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b7f3043fad27"
down_revision = "19b0c0697f0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("recipe", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "recipe")
    # ### end Alembic commands ###
