"""add todo_links table

Revision ID: 245e10c85a50
Revises: 64d70dadbe1a
Create Date: 2026-05-03 14:33:32.128481

"""

import re

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "245e10c85a50"
down_revision = "64d70dadbe1a"
branch_labels = None
depends_on = None

# Pattern to parse '[label](url)' strings
_PARSE_LINK_RE = re.compile(r"^\[([^\]]*)\]\(([^)\s]+)\)$")


def _normalize_url(url: str) -> str:
    """Prepend http:// when url has no scheme."""
    from urllib.parse import urlparse

    return url if urlparse(url).scheme else f"http://{url}"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todo_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("todo_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["todo_id"],
            ["todos.id"],
            name=op.f("fk_todo_links_todo_id_todos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_todo_links")),
    )
    op.create_index("ix_todo_links_todo_id", "todo_links", ["todo_id"], unique=False)

    # Migrate existing links from todos.links array to todo_links table
    conn = op.get_bind()

    # Get all todos with non-empty links
    result = conn.execute(
        sa.text("""
            SELECT id, links
            FROM todos
            WHERE links IS NOT NULL AND links != '{}'::text[]
        """)
    )

    for todo_id, links_array in result:
        if not links_array:
            continue

        for position, link_str in enumerate(links_array):
            # Parse the '[label](url)' format
            match = _PARSE_LINK_RE.match(link_str)
            if not match:
                # If it doesn't match the expected format, treat entire string as URL
                url = _normalize_url(link_str)
                label = None
            else:
                label = match.group(1) or None
                url = _normalize_url(match.group(2))

            # Insert into todo_links table
            conn.execute(
                sa.text("""
                    INSERT INTO todo_links (todo_id, label, url, position)
                    VALUES (:todo_id, :label, :url, :position)
                """),
                {"todo_id": todo_id, "label": label, "url": url, "position": position},
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Migrate data back from todo_links to todos.links array
    conn = op.get_bind()

    # Get all links and convert back to array format
    result = conn.execute(
        sa.text("""
            SELECT todo_id, label, url, position
            FROM todo_links
            ORDER BY todo_id, position
        """)
    )

    # Build a dictionary of todo_id -> list of link strings
    todo_links = {}
    for todo_id, label, url, position in result:
        if todo_id not in todo_links:
            todo_links[todo_id] = []

        if label:
            link_str = f"[{label}]({url})"
        else:
            link_str = url
        todo_links[todo_id].append(link_str)

    # Update each todo with the migrated links
    for todo_id, link_strings in todo_links.items():
        conn.execute(
            sa.text("""
                UPDATE todos
                SET links = ARRAY[:links]::text[]
                WHERE id = :todo_id
            """),
            {"todo_id": todo_id, "links": link_strings},
        )

    op.drop_index("ix_todo_links_todo_id", table_name="todo_links")
    op.drop_table("todo_links")
    # ### end Alembic commands ###
