"""make todo owners mandatory

Revision ID: f259066775a8
Revises: 9a43530c7474
Create Date: 2026-05-06 07:09:18.611833

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f259066775a8"
down_revision = "9a43530c7474"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        update todos set owner_id = (select min(id) from users where is_admin = true) where owner_id is null
    """)
    op.alter_column("todos", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("todos", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
