"""make todo owners mandatory

Revision ID: 9a43530c7474
Revises: 245e10c85a50
Create Date: 2026-05-06 06:55:03.196483

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9a43530c7474"
down_revision = "245e10c85a50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pk_config_items", "config_items", type_="primary")
    op.create_primary_key("pk_config_items", "config_items", ["key"])
    op.alter_column("config_items", "value", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("config_items", "value", existing_type=sa.TEXT(), nullable=False)
    op.drop_constraint("pk_config_items", "config_items", type_="primary")
    op.create_primary_key("pk_config_items", "config_items", ["key", "value"])
    # ### end Alembic commands ###
