"""allow shared attachment files across recurrences

Revision ID: a9df32556402
Revises: f259066775a8
Create Date: 2026-05-10 12:13:48.036763

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a9df32556402"
down_revision = "f259066775a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_todo_attachments_uuid", "todo_attachments", type_="unique")
    op.create_index(
        "ix_todo_attachments_uuid", "todo_attachments", ["uuid"], unique=False
    )
    op.alter_column("todos", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("todos", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_index("ix_todo_attachments_uuid", table_name="todo_attachments")
    op.create_unique_constraint(
        "uq_todo_attachments_uuid", "todo_attachments", ["uuid"]
    )
    # ### end Alembic commands ###
