"""add todo_attachments

Revision ID: de613bd28fbf
Revises: f316f0e748c4
Create Date: 2026-04-28 23:04:10.201482

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de613bd28fbf"
down_revision = "f316f0e748c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todo_attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("todo_id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("mimetype", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["todo_id"],
            ["todos.id"],
            name=op.f("fk_todo_attachments_todo_id_todos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_todo_attachments")),
        sa.UniqueConstraint("uuid", name=op.f("uq_todo_attachments_uuid")),
    )
    op.create_index(
        "ix_todo_attachments_todo_id", "todo_attachments", ["todo_id"], unique=False
    )
    op.drop_index("ix_todos_status", table_name="todos", if_exists=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_todo_attachments_todo_id", table_name="todo_attachments")
    op.drop_table("todo_attachments")
    # ### end Alembic commands ###
